web:
  image: mback2k/django-bawebauth
  links:
   - db
   - redis
  ports:
   - "8000:8000"
  volumes:
   - .:/app
  environment:
    DJANGO_PERFORM_SETUP: "yes"
  command: /usr/bin/python3 manage.py runserver 0.0.0.0:8000
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
redis:
  image: redis
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   - PMA_ARBITRARY=1
  links:
   - db:mariadb
  ports:
   - "8080:8080"
